export const day1Scene = {
  id: 'day1',
  title: 'Day One: The Signal',
  location: {
    place: 'Virescent City',
    level: 'Level 10 — Residential District',
    time: 'Day One: Week 49: 3105  08:03',
  },
  narrative: [
    { type: 'text', content: 'When you leave your apartment a few hours later, the city feels slightly off, as if someone nudged it half a degree to the left.' },
    { type: 'break' },
    { type: 'text', content: 'The air tastes metallic.\nThe transit announcements echo with a faint undertone you just can\'t place. It\'s familiar, yet unsettling.\nEven the people seem slower. It\'s almost as if they\'re moving on a delay.' },
    { type: 'break' },
    { type: 'text', content: 'On your way to work, your comm vibrates intensely on your wrist.\nIt\'s a proximity alert.\nSomething with a signal signature matching the mysterious message you received a few hours ago is nearby.' },
    { type: 'break' },
    { type: 'text', content: 'Close enough for your small comm chip to pick it up.\nYet you don\'t immediately see anything that would be a red flag.' },
    { type: 'break' },
    { type: 'text', content: 'You turn around on the tram and see what you can find.\nYou see a maintenance drone hovering motionless under a streetlamp. An elderly vendor opening their street stall. A stairwell leading down to the lower restricted levels.' },
    { type: 'break' },
    { type: 'text', content: 'And then you pass a wall-sized billboard ad.\nNothing out of the ordinary. A normal daily dose of Collective propaganda.' },
    { type: 'break' },
    { type: 'text', content: 'But then it glitches.\nIt\'s subtle, but definitely there.\nThe same frame repeats momentarily every few seconds.\nIf only you could slow down time to see it more clearly…' },
    { type: 'break' },
    { type: 'text', content: 'And then it\'s gone. You\'re past the area and the vibration ceases. A moment later the tram slows to a stop — not your own — but you are compelled to get off.' },
    { type: 'break' },
    { type: 'text', content: 'Something about that billboard was wrong.' },
    { type: 'break' },
    { type: 'text', content: 'You exit the tram and jog back up the street a few blocks towards that ad.' },
    { type: 'break' },
    { type: 'text', content: 'The vibration returns to your comm, buzzing your wrist.\nAs the signal strengthens, so does the intensity of the vibration.' },
    { type: 'break' },
    { type: 'text', content: 'Your wrist buzzes violently by the time you stand below the large illuminated billboard.' },
    { type: 'break' },
    { type: 'text', content: 'And then a sound begins.' },
    { type: 'break' },
    { type: 'text', content: 'It\'s almost inaudible — a low drone, almost like an underground generator humming several miles away. Not the steady hum of the Virescent City power grid. This is different.' },
    { type: 'break' },
    { type: 'text', content: 'You listen.\nIs that a pattern?' },
    { type: 'break' },
    { type: 'text', content: 'You look around to see if anyone else seems to notice.\nIf they do, they don\'t show it.\nEveryone is walking right past you as if nothing out of the ordinary is happening at all.' },
    { type: 'break' },
    { type: 'text', content: 'You listen again.\nYes… it is a pattern.' },
    { type: 'break' },
    { type: 'text', content: 'A slow three-tone sequence that repeats itself.\nIt\'s low. Far lower than you\'d expect from this part of town.\nIt\'s almost human.' },
    { type: 'break' },
    { type: 'text', content: 'You check the crowd again, but no one reacts.' },
    { type: 'break' },
    { type: 'text', content: 'Are you crazy?\nNo…\nYou definitely hear it.' },
    { type: 'break' },
    { type: 'text', content: 'And it feels like it\'s coming from beneath the street, not the billboard itself.' },
    { type: 'break' },
    { type: 'text', content: 'You pause and the maintenance drone rotates towards you.' },
    { type: 'break' },
    { type: 'text', content: 'It emits a quick pulse of green light.\nNot a scan signal.\nIt\'s just a laser pointing…' },
    { type: 'text', content: 'Directly at the stairwell leading down into the deeper restricted access levels.' },
    { type: 'text', content: 'Beneath the street.' },
    { type: 'break' },
    { type: 'text', content: 'Is it speaking to you?\nThat can\'t be. Maintenance drones don\'t interact with people. They just… well, work.\nThey fix things.' },
    { type: 'break' },
    { type: 'text', content: 'But this one is definitely signaling for you to go down the stairs… right?' },
    { type: 'break' },
    { type: 'text', content: 'You think about how crazy this is.\nNo one in their right mind would think a laser pointer from a rogue maintenance drone is meant for them.' },
    { type: 'break' },
    { type: 'text', content: 'They. Fix. Things.' },
    { type: 'break' },
    { type: 'text', content: 'Then your comm vibrates three quick pulses.\nA new message:' },
    { type: 'comm', content: '"WE ARE BELOW. FOLLOW THE SIGNAL."' },
    { type: 'break' },
    { type: 'text', content: 'Your breath catches in your chest.' },
    {
      type: 'echo',
      journalKey: 'prologue_q5',
      prefix: 'You feel it again — that strange first feeling from last night. ',
      suffix: ' It sits heavy in your chest.',
      fallback: null,
    },
    { type: 'break' },
    { type: 'text', content: 'The drone is speaking to you.\nOr rather, whoever is sending these messages is speaking to you.\nRight?' },
    { type: 'break' },
    { type: 'text', content: 'You look at your comm again and the message is gone.\nJust like before.' },
    { type: 'break' },
    { type: 'text', content: 'You look at the stairwell leading to the lower levels.\nA place you haven\'t visited in years.\nNot since the incident…' },
    { type: 'break' },
    { type: 'text', content: 'The signal pulses again.\nThree human-like tones vibrating all around you.\nA low hum that you feel to your very core.' },
    { type: 'break' },
    { type: 'text', content: 'Whatever this is…\nIt wants you to go down those stairs.' },
  ],
  prompts: [
    {
      id: 'day1_q1',
      number: 'I',
      text: 'Describe the exact moment you realize the signal is calling you specifically. What does that make you feel?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day1_path',
      number: 'II',
      text: 'You must choose: follow the signal down the stairwell into restricted levels, or refuse and investigate one of the anomalies nearby.',
      isPathChoice: true,
      choices: [
        {
          value: 'A',
          label: 'Follow the signal',
          description: 'Descend into the restricted stairwell. Whatever is calling to you — you answer.',
        },
        {
          value: 'B',
          label: 'Refuse and investigate',
          description: 'Stay above ground. Investigate the drone, the vendor, or the glitching billboard on your own terms.',
        },
      ],
    },
    {
      id: 'day1_q2',
      number: 'III',
      text: 'Journal the reason behind your choice. Focus on instinct, emotion, the memories it stirs.',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day1_q3',
      number: 'IV',
      text: 'Something unexpected happens because of your choice. Select one anomaly and describe it as if you\'re noticing it gradually — like someone waking from a dream.',
      isAnomalyChoice: true,
      choices: [
        'A reflection behaves oddly',
        'A voice speaks from a broken device',
        'The stairwell is far deeper than it should be',
        'A map or sign changes as you get closer',
        'A stranger stares at you far too long, then looks away as if they recognize you',
        
      ],
    },
    {
      id: 'day1_q4',
      number: 'V',
      text: 'End your entry with a line that begins with:',
      endingPrefix: '"I have a feeling that going below will cost me…"',
      placeholder: '"I have a feeling that going below will cost me…"',
    },
  ],
  nextScene: (state) => state.path === 'A' ? 'day2a' : 'day2b',
}
