export const day7Scene = {
  id: 'day7',
  title: 'Day Seven: The Truth',
  dayNumber: 7,
  location: {
    place: 'Virescent City',
    level: 'Level ???',
    time: 'Day Three: Week 50: 3105  23:58',
  },
  convergenceNote: 'Both paths converge here.',
  narrative: [
    { type: 'text', content: 'You walk through the dimly lit corridor with your head held high. You made your choice. You know it\'s the right one. Sure, there\'s a small part of you that is questioning it, but anyone would have that doubt.' },
    { type: 'break' },
    { type: 'text', content: 'You tried to find an exit.\nA way to end this charade — this nightmare.\nYou tried to live out the decision you made.' },
    { type: 'break' },
    { type: 'text', content: 'Unfortunately, that didn\'t work. The city seemed to give you the cold shoulder. So did the messengers. Your comm has been dormant for days now.' },
    { type: 'break' },
    { type: 'text', content: 'You\'re not really sure how you ended up here.\nLast thing you remember is heading back to your apartment to get some sleep when you\'d reached the point of exhaustion that was unbearable.' },
    { type: 'break' },
    { type: 'text', content: 'Did you ever make it back?\nYou slept in your bed, right?' },
    { type: 'break' },
    { type: 'text', content: 'You rack your brain, but you can\'t remember. It\'s fuzzy, like you wiped your history. It doesn\'t matter anyway. You\'re here now. That\'s what matters.' },
    { type: 'break' },
    { type: 'text', content: 'You rub the bridge of your nose, which makes you realize how strange this place smells.' },
    { type: 'break' },
    { type: 'text', content: 'It\'s clean.\nLike a hospital, but worse.\nThe air almost has a sickly sweetness to it.\nIt\'s nauseating when you pause to truly experience it.' },
    { type: 'break' },
    { type: 'text', content: 'The temperature is completely neutral, which is annoying. You\'d prefer to feel something, but it\'s like everything in this godforsaken city is being taken from you. Like it\'s been designed to make you go mad. To question your very existence.' },
    { type: 'break' },
    { type: 'text', content: 'You keep marching forward.\nOne foot in front of the other.\nThe concrete walls seem to go on forever.\nYou forget how long you\'ve been here.' },
    { type: 'break' },
    { type: 'text', content: 'Not just here, in this hallway.\nHere, as in…\nAlive.' },
    { type: 'break' },
    { type: 'text', content: 'Your comm buzzes on your wrist for the first time in days. You\'d almost assumed it was dead at this point. You flick your wrist instinctively and see that it\'s a navigation notification.' },
    { type: 'break' },
    { type: 'text', content: 'What?' },
    { type: 'break' },
    { type: 'text', content: 'The chevron on the screen representing your location is pointing straight ahead. Every few steps the comm vibrates lightly. This goes on for a long time. Too long.' },
    { type: 'break' },
    { type: 'text', content: 'Then it nearly vibrates off your arm and the chevron points right.\nYou stop, pull the comm back onto your wrist, and turn to look at the wall to your right.\nSure enough, there\'s an imprint in the wall where a door handle would be. That\'s the only detail you notice. The wall looks completely plain otherwise. No indication that it could move in or out.' },
    { type: 'break' },
    { type: 'text', content: 'Just the impression.\nEasily missed.\nExcept someone or something notified you.' },
    { type: 'break' },
    { type: 'text', content: 'You reach out and touch it.\nA burning sensation washes over your body from head to toe and everything goes black.\nJust for a moment.\nThen it passes.' },
    { type: 'break' },
    { type: 'text', content: 'And you find yourself in a small room…' },
    { type: 'break' },
    { type: 'text', content: 'It\'s the exact opposite of everything you\'ve been experiencing for days on end. It\'s decorated with ornate bookshelves that go floor to ceiling, made from a dark material that you don\'t recognize. There\'s a massive fireplace on one wall, directly in the center, and it has a roaring fire. The wave of heat nearly makes you pass out. You fan yourself and suddenly feel sweat beading on your forehead.' },
    { type: 'break' },
    { type: 'text', content: 'There\'s a large wooden desk to the right of the fireplace with papers and books scattered over it, but in neat piles. Almost as if someone has been doing research. Organized research.' },
    { type: 'break' },
    { type: 'text', content: 'The other side of the room has two large couches made from a tan material that looks like… skin? There\'s a small table in front of them with two mugs of steaming liquid. You think about grabbing one and downing it, but you hesitate.' },
    { type: 'break' },
    { type: 'text', content: 'Directly in front of you is a tall chair with its back to you, facing the fire. The room smells of smoke and wood and tea. Compared to the stale world you\'ve been in, this feels like sensory overload.' },
    { type: 'break' },
    { type: 'text', content: '"We\'ve been waiting."' },
    { type: 'break' },
    { type: 'text', content: 'You freeze.\nYour heart skips several beats and you pound your chest, lest it not turn back on.\nYou feel sick and the desire to run, but the realization that there\'s nowhere to go balances that out.' },
    { type: 'break' },
    { type: 'text', content: 'You ask who\'s there.\nThey respond that you know.' },
    { type: 'break' },
    { type: 'text', content: '"I don\'t know," you reply, annoyed at the audacity.' },
    { type: 'break' },
    { type: 'text', content: '"But you do. You\'ve always known."' },
    { type: 'break' },
    { type: 'text', content: '"Stop playing games!"' },
    { type: 'break' },
    { type: 'text', content: '"We know you know. We\'ve been here, waiting, down below. We know you know."' },
    { type: 'break' },
    { type: 'text', content: '"Know what?" you ask.' },
    { type: 'break' },
    { type: 'text', content: '"Tell us what you decided. Tell us your choice."' },
    { type: 'break' },
    { type: 'text', content: 'You\'re seething at this point.\nHow dare they? Who do they think they are?' },
    { type: 'break' },
    { type: 'text', content: 'Who do they think you are?\nNow that\'s the question…' },
    { type: 'break' },
    { type: 'text', content: 'You try telling them that you don\'t know who they are or what decision they are talking about, but no one answers you. You think about spinning the chair around, but realize it\'s fixed to the floor. You could walk around, but the heat from the fireplace is too much to bear.' },
    { type: 'break' },
    { type: 'text', content: 'How is that blaze so large and not melting the chair or the nearby books?' },
    { type: 'break' },
    { type: 'text', content: 'Annoyed, you blurt out the reality you chose to grip onto.\nYou spill the entire contents of your emotional guts to them.\nNo detail is spared in how you made the decision, why that matters to you, and what you plan to do about it.' },
    {
      type: 'echo',
      journalKey: 'day6a_q3',
      prefix: 'You hear yourself saying it again — the decision you wrote down after all of it: ',
      suffix: ' — the words feel strange out loud, but they are yours.',
      altKey: 'day6b_q3',
      fallback: null,
    },
    { type: 'break' },
    { type: 'text', content: 'It\'s hard to catch your breath when you\'re finished ranting. Your heart is pounding in your ears and against your chest so hard you think it could explode.' },
    { type: 'break' },
    { type: 'text', content: 'Maybe that would be for the best…\nNo, you don\'t believe that.\nRight?' },
    { type: 'break' },
    { type: 'text', content: 'After what feels like forever, the voice replies.\nYou don\'t hear what it says at first.\nInstead you realize how it sounds.\nThe tone and cadence.\nThey\'re familiar.\nEerily so.' },
    { type: 'break' },
    { type: 'text', content: '"Did you hear that?" they ask.' },
    { type: 'break' },
    { type: 'text', content: 'You reply that you did not and wipe your forehead with your forearm. The sweat is pouring now.' },
    { type: 'break' },
    { type: 'text', content: '"The truth is a tricky business. Some would have you believe that whatever you think is true, is in fact the truth. Your truth. My truth. It\'s all equal.\n\nOthers would have you believe that truth is objective.\nTruth cares not what you believe.\nIt knows itself more fully than you\'ll ever comprehend."' },
    { type: 'break' },
    { type: 'text', content: 'You shake your head and raw emotion boils inside your gut.' },
    { type: 'break' },
    { type: 'text', content: 'The voice continues, "What you believe to be true is not the end of the matter. What if you made the wrong choice?\n\nWhat if your truth is wrong?"' },
    { type: 'break' },
    { type: 'text', content: 'No.\nThat\'s not right.' },
    { type: 'break' },
    { type: 'text', content: 'You shout and say exactly how you feel, but the words might as well fall on deaf ears.' },
    { type: 'break' },
    { type: 'text', content: '"Believe what you must.\nWe will not stop you.\nBut…\nYou must consider how that belief will make a difference.\nWhat will you do with it?\nAnd if you are wrong, what happens then?"' },
    { type: 'break' },
    { type: 'text', content: '"I don\'t know," you mutter, nearly inaudibly.' },
    { type: 'break' },
    { type: 'text', content: '"Think back. What is the oldest memory you have?"' },
    { type: 'break' },
    { type: 'text', content: 'You try to think, but the suffocating heat of the room and the hurricane of thoughts swirling around your head are too much.' },
    { type: 'break' },
    { type: 'text', content: '"THINK! WHAT IS IT?"' },
    { type: 'break' },
    { type: 'text', content: 'You rub your temples.\nYour head feels like it\'ll split open.\nYou know the answer, but you don\'t want to admit it.\nYou can\'t admit it.\nNot that.\nAnything but that.' },
    { type: 'break' },
    { type: 'text', content: 'The light pulses in the room.\nJust like before.' },
    { type: 'break' },
    { type: 'text', content: 'Has it always been green?' },
    { type: 'break' },
    { type: 'text', content: 'The wrong memory floods your mind. You cry out in agony, in despair, in sadness — then triumph? You laugh. At first it starts as one chuckle, but it builds to an uncontrollable laughter that takes your breath and gives you a stitch in your side.' },
    {
      type: 'echo',
      journalKey: 'char.strangeMemory',
      prefix: 'And there it is — the memory that was never yours: ',
      suffix: ' — and for one terrible second, it feels more real than anything else in this room.',
      fallback: null,
    },
    { type: 'break' },
    { type: 'text', content: 'The voice laughs as well.\nIt resonates throughout the room like a vibration.\nYou\'ve heard it before, this laugh, but you didn\'t know what it was.' },
    { type: 'break' },
    { type: 'text', content: 'But it can\'t be…\nCan it?' },
    { type: 'break' },
    { type: 'text', content: 'But what if it is?\nYes… it could be.' },
    { type: 'break' },
    { type: 'text', content: 'Without thinking you grab a hold of the chair and launch yourself over it, landing between the front of the chair and the roaring fire. The heat stings immediately, but you don\'t care.' },
    { type: 'break' },
    { type: 'text', content: 'Only one thing matters now.\nBut…\nWhat you see is not what you are expecting.\nIt leaves more questions than answers.' },
    { type: 'break' },
    { type: 'text', content: 'Your head swims.\nWhat they said sounds right…\nFeels right.\nBut it\'s not… no, it can\'t be.' },
    { type: 'break' },
    { type: 'text', content: 'This isn\'t right.\nIt can\'t be right.\nWe can\'t be right.\nWe can\'t be…' },
    { type: 'break' },
    { type: 'text', content: 'You try to speak, but no sound comes.\nJust the sound of metallic clicking.\nLike an old wall clock.\nLike a broken echo.' },
    { type: 'break' },
    { type: 'text', content: 'Your comm buzzes on your wrist, yanking you back into the moment.\nYou look.\nYou can\'t help it.\nIt\'s built into you like an automation.' },
    { type: 'break' },
    { type: 'text', content: 'The message appears for but a moment:' },
    { type: 'comm', content: '"Do you know yet?"' },
  ],
  prompts: [
    {
      id: 'day7_q1',
      number: 'I',
      text: 'Write the internal dialogue your character has when they recognize the voice for the first time. Who or what is it? What does that make them feel?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day7_q2',
      number: 'II',
      text: 'Describe what they saw when they vaulted over the chair. How did it differ from what they were expecting? What does it mean for their journey?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day7_q3',
      number: 'III',
      text: 'Does your character know what the message on the comm is referring to? What do they think it means? How does the story end?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day7_q4',
      number: 'IV',
      text: 'Artifact of the day — create or describe one additional artifact from this experience:',
      isAnomalyChoice: true,
      choices: [
        'Something hanging above the mantle that shouldn\'t be there',
        'Cameras in the corner of the room',
        'Busted comms scattered all around the room',
        'Letters written in your own handwriting — except you\'ve not written them',
        'A security breach warning announcement',
      ],
    },
    {
      id: 'day7_q5',
      number: 'V',
      text: 'What if your character was the copy the entire time? What evidence would they use to disprove it? What memories would they draw on? How does the "false" memory affect it?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'day7_q6',
      number: 'VI',
      text: 'End your entry with a line that leaves the story open-ended.',
      placeholder: 'Write the final line of your chronicle…',
    },
  ],
  nextScene: 'epilogue',
}
