// Path A: The Descent — Days 2 through 6

export const pathAScenes = [
  {
    id: 'day2a',
    title: 'Day Two: The Descent',
    path: 'A',
    dayNumber: 2,
    location: {
      place: 'Virescent City',
      level: 'Level 09 — Restricted Access',
      time: 'Day One: Week 49: 3105  09:32',
    },
    narrative: [
      { type: 'text', content: 'You make your way to the stairwell, looking around to make sure no one is watching.\nYou glance up at the street lamps looking for cameras.\nThere are none.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s odd. They always have cameras near these types of stairwells, don\'t they?' },
      { type: 'break' },
      { type: 'text', content: 'The drone stops pointing the green laser.\nNo one on the street seems to be paying attention to you. Like normal, they\'re all engrossed in whatever their personal heads up displays are showing them.' },
      { type: 'break' },
      { type: 'text', content: 'You take a deep breath and look down into the darkness.' },
      { type: 'break' },
      { type: 'text', content: 'How many times have you passed this very stairwell on your daily commute and never noticed it?\nHundreds at least.\nPossibly thousands.' },
      { type: 'break' },
      { type: 'text', content: 'Yet, here it is. A descent into the darkness of Virescent City\'s restricted levels.' },
      { type: 'break' },
      { type: 'text', content: '"There\'s no use fighting it now," you think, and plunge yourself into the darkness.' },
      { type: 'break' },
      { type: 'text', content: 'It swallows you whole.\nWithin seconds you can\'t see anything.\nThis isn\'t like the upper levels that have stairwells meant for heavy foot traffic.\nNo.\nThis is meant to go unnoticed.\nTop. Secret.' },
      { type: 'break' },
      { type: 'text', content: 'The door slams shut behind you and echoes loudly down into the darkness.\nThe stairwell grows colder with each step.\nYou fish around your right trouser pocket and pull out a small flashlight.\n200 lumens have never been so powerful.' },
      { type: 'break' },
      { type: 'text', content: 'You expected to see signage or hazard warnings or — well, anything on the walls here. But they\'re completely bare.\nNaked concrete.\nUnfinished.\nAs if the people building the city abandoned construction hundreds of years ago.' },
      { type: 'break' },
      { type: 'text', content: 'Suddenly your comm vibrates firmly on your wrist.\nYou jump and shout a word your mother would have slapped you for saying.' },
      { type: 'break' },
      { type: 'text', content: 'The signal strengthens.\nSo does the vibration.' },
      { type: 'break' },
      { type: 'text', content: 'You press on.\nDownward.\nEver downward.' },
      { type: 'break' },
      { type: 'text', content: 'After what feels like way too long you realize something unsettling.' },
      { type: 'break' },
      { type: 'text', content: 'Your footsteps echo wrong.\nYou step once and listen.\nThe echo repeats twice.' },
      { type: 'break' },
      { type: 'text', content: 'Your heart races suddenly and you turn around shining the light behind you.' },
      { type: 'break' },
      { type: 'text', content: 'No one\'s there.' },
      { type: 'break' },
      { type: 'text', content: 'You take another step and the broken echo comes again as if someone is right behind you, mimicking your pace — just a fraction of a second too late.' },
      { type: 'break' },
      { type: 'text', content: 'You turn once more and check for something behind, but again, nothing is there.' },
      { type: 'break' },
      { type: 'text', content: 'You wonder how long these stairs are going to continue downward.\nYou wonder how long you\'ve been going down them.\nYou check your comm, but the screen is just static.' },
      { type: 'break' },
      { type: 'text', content: 'You decide to get off as soon as you find the next landing.' },
      { type: 'break' },
      { type: 'text', content: 'Then you see it.' },
      { type: 'break' },
      { type: 'text', content: 'A few steps down from you.\nJust there, on the right.\nA smear of green light on the wall.\nNot paint.\nNot graffiti.' },
      { type: 'break' },
      { type: 'text', content: 'You get closer.' },
      { type: 'break' },
      { type: 'text', content: 'Yes, it\'s a thin, luminescent residue.\nAnd it\'s pulsing… with the same three-tone pattern you heard above.' },
      { type: 'break' },
      { type: 'text', content: 'Your heart pounds against your chest and you feel the goosebumps forming on your arms.' },
      { type: 'break' },
      { type: 'text', content: 'You lean in closer to examine it.\nThat\'s when you see an object lying on the step just below the luminescence.' },
      { type: 'break' },
      { type: 'text', content: 'A wrist comm.\nYou pick it up and look it over.\nScorched.\nBroken.\nThe titanium band torn in two.' },
      { type: 'break' },
      { type: 'text', content: 'These things are supposed to be indestructible.\nApparently not.' },
      { type: 'break' },
      { type: 'text', content: 'The name tag on the back is melted, but one letter remains clear:' },
      { type: 'break' },
      { type: 'text', content: '"L"' },
      { type: 'break' },
      { type: 'text', content: 'You know someone whose name begins with L.\nSomeone you haven\'t heard from in weeks…' },
      {
        type: 'echo',
        journalKey: 'char.incident',
        prefix: 'The memory of the incident surfaces — ',
        suffix: ' — and suddenly the weight of it is back, pressing on your chest like concrete.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'You take another step.\nThe hair suddenly stands up on the back of your neck.' },
      { type: 'break' },
      { type: 'text', content: 'The echo stopped behind you.' },
    ],
    prompts: [
      {
        id: 'day2a_q1',
        number: 'I',
        text: 'Describe the exact thought you have when you see the matching wristband and the letter "L" on the melted nameplate. Is it fear? Recognition? Guilt? Or something else?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day2a_q2',
        number: 'II',
        text: 'Journal how your character rationalizes the impossible architecture of the endless stairwell. Do they treat it as an anomaly? A glitch? Are they imagining it? Have the stairwells always been this way and they never noticed?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day2a_q3',
        number: 'III',
        text: 'Choose one follow-up anomaly and describe how you approach or avoid it:',
        isAnomalyChoice: true,
        choices: [
          'The green residue forms a symbol from your memories before your eyes',
          'The echo begins responding out of sync, forming its own rhythm before returning to mismatching your own',
          'A voice whispers from the steps below: "You\'re late."',
          'The stairwell abruptly ends at a blank concrete wall',
        ],
      },
      {
        id: 'day2a_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"If someone I know came down here before me… then I am already too late."',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day3a',
  },

  {
    id: 'day3a',
    title: 'Day Three: The Symmetry Below',
    path: 'A',
    dayNumber: 3,
    location: {
      place: 'Virescent City',
      level: 'Level 0? — Unregistered Access Shaft',
      time: 'Day Two: Week 49: 3105  02:07',
    },
    narrative: [
      { type: 'text', content: 'You descend for what feels like an eternity.' },
      { type: 'break' },
      { type: 'text', content: 'How long have you been going down these stairs anyway?\nYou look at your comm expecting the blank static screen, but instead the readout says it\'s 2:07 in the morning.' },
      { type: 'break' },
      { type: 'text', content: 'What the hell?' },
      { type: 'break' },
      { type: 'text', content: 'Last you checked it was Day One at nine in the morning — and now it\'s somehow Day Two at two in the morning?\nThat can\'t be.\nSurely not, right?' },
      { type: 'break' },
      { type: 'text', content: 'You tap the comm screen and it goes static again, like it can\'t communicate with the neural network.\nThe only other time you\'ve seen this happen is when you were quite literally off planet and it was fully disconnected.' },
      { type: 'break' },
      { type: 'text', content: 'But you\'re not off planet… right?' },
      { type: 'break' },
      { type: 'text', content: 'The air here isn\'t right.\nIt tastes stale and metallic — almost recycled.\nIt\'s not particularly cold or warm on your skin either, just sort of neutral.' },
      { type: 'break' },
      { type: 'text', content: 'You can\'t help but realize once again that the weird echo from before has gone completely. It\'s bothering you more than you\'d like, always nagging at the back of your mind.' },
      { type: 'break' },
      { type: 'text', content: 'Why did it stop?\nWhere was it coming from?\nAm I crazy?' },
      { type: 'break' },
      { type: 'text', content: 'And let\'s not forget that you really shouldn\'t have been walking this long without coming to at least one landing, an access hatch, a service tunnel — something.' },
      { type: 'break' },
      { type: 'text', content: 'Instead, it\'s just endless concrete.\nEndless steps.\nEndless echoes into endless darkness.' },
      { type: 'break' },
      { type: 'text', content: 'Then things change.\nNot all at once, but gradually, like the opening of an ancient concerto. It starts so small you might not realize anything had changed at all — but then the walls seem further apart slightly.' },
      { type: 'break' },
      { type: 'text', content: 'You reach your arms out to either side as wide as your wingspan will allow.\nBut you can\'t touch both sides anymore.' },
      { type: 'break' },
      { type: 'text', content: 'You definitely could a few moments before.\nThe passage was always narrow enough that you could place the palms of your hands on both walls at the same time.\nNow, it was too wide to do so.' },
      { type: 'break' },
      { type: 'text', content: 'It\'s as if the walls are suddenly breathing outward to make space for something larger than you. Your light flickers across new shapes — rusted rails, broken conduits, panels dangling by threads of wiring.' },
      { type: 'break' },
      { type: 'text', content: 'What is this place?' },
      { type: 'break' },
      { type: 'text', content: 'A few more steps down and you reach a landing.\nFlat ground.\nOh blessed be the gods, flat ground.' },
      { type: 'break' },
      { type: 'text', content: 'Just ahead a corridor branches off to the right. You slowly make your way towards it and a thought occurs to you.' },
      { type: 'break' },
      { type: 'text', content: 'This corridor is impossible.\nI must be miles below Level 01 at this point.' },
      { type: 'break' },
      { type: 'text', content: 'You turn the corner and discover a perfectly symmetrical hallway. The walls, floor tiles, ceiling panels and lights are all so precise it feels artificial. Manufactured. Wrong.' },
      { type: 'break' },
      { type: 'text', content: 'You turn your flashlight off and stick it back in your pocket.\nYou blink a few times and allow your eyes to adjust.\nThough the light is dim, it\'s still brighter than 200 lumens and overpowering your senses.\nYou rub your eyes and blink one final time, finally feeling acclimated to the new brightness.' },
      { type: 'break' },
      { type: 'text', content: 'And that\'s when you see it.' },
      { type: 'break' },
      { type: 'text', content: 'At the far end of the corridor, illuminated by a pale, greenish light, you see a door.\nA simple, unmarked door.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s quite odd, but even more strange is the thing standing in front of it…' },
      { type: 'break' },
      { type: 'text', content: 'You squint to be sure, because it\'s not possible to be what you thought it was at first glance.' },
      { type: 'break' },
      { type: 'text', content: 'You take a few steps towards it and pull your flashlight back out, just to be sure.\nYour heart stops.' },
      { type: 'break' },
      { type: 'text', content: 'It\'s you.\nSame height.\nSame posture.\nSame clothes.' },
      { type: 'break' },
      { type: 'text', content: 'Except… it\'s not you.' },
      { type: 'break' },
      { type: 'text', content: 'The figure mirrors your stance, but not perfectly.\nIt\'s off, just slightly.\nIt\'s like it\'s a half beat behind the real you.' },
      { type: 'break' },
      { type: 'text', content: 'Just like the echo on the stairs…' },
      { type: 'break' },
      { type: 'text', content: 'A broken reflection of a real person.\nA copy made by someone, or something, that has seen you, but doesn\'t fully understand you.' },
      { type: 'break' },
      { type: 'text', content: 'You blink and the figure blinks half a second later.\nYou raise your flashlight and it does the same, ever so slightly behind.' },
      { type: 'break' },
      { type: 'text', content: 'You tilt your head to the side and it follows.\nThat\'s when you see it. The face is blurred slightly.\nAlmost as if it\'s not fully rendered. As if reality hadn\'t fully committed itself to this copy.' },
      { type: 'break' },
      { type: 'text', content: 'Your breath catches and your heart hammers in your ears.\nThat\'s when the echo returns.\nBehind you.\nBut this time, it\'s not following your footsteps… it\'s following theirs.' },
      { type: 'break' },
      { type: 'text', content: 'The copy tilts its head, like it\'s studying you now.\nWith curiosity.\nWith creepy admonition.' },
      { type: 'break' },
      { type: 'text', content: 'It smiles and takes a step towards you.\nThe green light behind the door pulses once.' },
      { type: 'break' },
      { type: 'text', content: 'Then it takes another step and the light pulses again. In your core you know the two are connected, but you can\'t figure how.\nNot yet.\nThat\'ll take time.' },
      { type: 'break' },
      { type: 'text', content: 'Then the whole corridor breathes.\nJust like your apartment did.\nJust like the city has been doing the entire time.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s when the not-right copy breaks out into a sprint…\nToward you.' },
    ],
    prompts: [
      {
        id: 'day3a_q1',
        number: 'I',
        text: 'When you realize the figure is a distorted version of yourself, what is your honest first reaction? Fear? Confusion? Anger? Curiosity?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day3a_q2',
        number: 'II',
        text: 'Describe one detail that proves the copy is not you. How does that ground your character — and why does that scare them?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day3a_q3',
        number: 'III',
        text: 'Choose one follow-up anomaly and describe how it unfolds — and how your body reacts before your mind does:',
        isAnomalyChoice: true,
        choices: [
          'The copy begins mimicking your thoughts, not just your actions',
          'Its shadow detaches and begins moving independently',
          'The door pulses green light wildly and opens slightly, though neither of you touched it',
          'The echo from behind starts speaking in your voice',
          'The corridor morphs around you as the copy sprints for you',
        ],
      },
      {
        id: 'day3a_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"If that copy is still in progress… what happens when it finishes?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day4a',
  },

  {
    id: 'day4a',
    title: 'Day Four: The Pursuit',
    path: 'A',
    dayNumber: 4,
    location: {
      place: 'Virescent City',
      level: 'Level 0? — Unknown Corridor',
      time: 'Day Two: Week 49: 3105  23:17',
    },
    narrative: [
      { type: 'text', content: 'The messy copy sprinted at you with uncanny speed. You didn\'t have enough time to think how to respond — your body merely reacted. Just as the copy dove in an attempt to tackle you, you jumped to the side, hitting the wall hard.' },
      { type: 'break' },
      { type: 'text', content: 'Your shoulder suddenly hurt, but that was better than whatever would\'ve happened if that thing had gotten you.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s when you took your chance and sprinted for the open door.\nThe green light still pulsates in the rhythm you\'ve been hearing since… Yesterday?\nThe one you heard in your apartment.\nThe one that got you into this mess.\nThe supernatural hum of something or someone who is trying to communicate with you.' },
      { type: 'break' },
      { type: 'text', content: 'You hear the copy scramble to its feet as you close in on the opening — on freedom.\nNo time to look back.' },
      { type: 'break' },
      { type: 'text', content: 'You sprint as hard as you can and reach your arm out to grab the edge of the door.\nThe thing is closing in on you, practically breathing down your neck.\nHow the hell is it so fast if it\'s a copy of you?' },
      { type: 'break' },
      { type: 'text', content: 'You give every ounce of energy left to get to that light before it can get you.\nYou reach the door and fling it open, sliding to a stop on the other side and turning to shut the door.' },
      { type: 'break' },
      { type: 'text', content: 'But you don\'t have to.' },
      { type: 'break' },
      { type: 'text', content: 'There is no door.\nJust a concrete wall.' },
      { type: 'break' },
      { type: 'text', content: 'You stare at it for a moment, breathing hard.\nYou know you just ran through a doorway, but there\'s literally nothing there.\nYou run your hand over the spot where there should be a door. It\'s smooth. Devastatingly smooth.' },
      { type: 'break' },
      { type: 'text', content: 'Whatever. You\'re safe from that copy.\nFor now.' },
      { type: 'break' },
      { type: 'text', content: 'You turn around and take in your surroundings. You\'re standing in a large room outfitted like a laboratory. Metal tables with various beakers and scientific equipment. Bookshelves and cabinets lining the walls, packed to the gills with files and books.' },
      { type: 'break' },
      { type: 'text', content: 'You realize how cold it is.\nAnd stale.\nThe air tastes oddly clean — almost chemical.' },
      { type: 'break' },
      { type: 'text', content: 'A chill runs up your spine, though you\'re not sure if it\'s fear or simply how cold it is.\nYou rub your arms on either side to warm yourself up and move forward into the room.\nAs you get closer to the nearest table, you realize the scattered papers are all full of notes and diagrams, but you can\'t make sense of any of it. It\'s almost like they\'re written in a foreign language.' },
      { type: 'break' },
      { type: 'text', content: 'But it\'s your handwriting.' },
      { type: 'break' },
      { type: 'text', content: 'Out of the corner of your eye you see an empty table with restraints. Above it are several tubes, canisters, and a large light bulb.\nPulsing green.' },
      { type: 'break' },
      { type: 'text', content: 'You jog over to get a better look.\nYou can\'t help yourself.' },
      { type: 'break' },
      { type: 'text', content: 'As you reach the table, the light is pulsing faster.\nAlmost like it senses your presence.\nYour comm buzzes and you glance at it quickly. It\'s just a heart rate notification. Any other time you\'d ignore it and move on, but something about it grips you.' },
      { type: 'break' },
      { type: 'text', content: 'The heart on the comm screen is flashing at the exact cadence the light is pulsating.' },
      { type: 'break' },
      { type: 'text', content: 'You feel your heart pound in your chest suddenly.\nThump, thump.\nThump, thump.\nThump, thump.' },
      { type: 'break' },
      { type: 'text', content: 'The light matches it.\nBeat\nFor\nBeat.' },
      { type: 'break' },
      { type: 'text', content: 'This is too weird. Why would the light here be matching your heart rate? That doesn\'t make any sense at all. You put your hands on your knees and swallow hard to keep the sick back.' },
      { type: 'break' },
      { type: 'text', content: 'Crash.' },
      { type: 'break' },
      { type: 'text', content: 'Somewhere behind you glass shatters.\nYou freeze. Is there someone else in this room? Dare you say anything?\nNo, best not.' },
      { type: 'break' },
      { type: 'text', content: 'You turn slowly and silently.\nA million thoughts race through your mind — most of them ways to escape… or fight.' },
      { type: 'break' },
      { type: 'text', content: 'But one thought sticks out.\nThe memory.\nThe one that doesn\'t make sense.\nThe one that lurks at the back of your mind, constantly.' },
      {
        type: 'echo',
        journalKey: 'char.strangeMemory',
        prefix: 'It surfaces again, unbidden: ',
        suffix: ' — you shove it back into the dark.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'No time for that now. You spin the rest of the way around and expect to find the copy ready to pounce.' },
      { type: 'break' },
      { type: 'text', content: 'But you don\'t.\nThe room is empty.\nNot empty as in there\'s no other person in there with you.\nEmpty.\nVoid of anything.' },
      { type: 'break' },
      { type: 'text', content: 'You spin around again to check behind you.\nThe table and all the stuff surrounding it are gone.\nThe walls are bare. Just plain concrete.\nAnd it\'s suddenly much darker than before. The air is still cold, but now it\'s damp against your skin.' },
      { type: 'break' },
      { type: 'text', content: 'You shiver and swallow hard.\nWhatever is happening is not okay.' },
      { type: 'break' },
      { type: 'text', content: 'You turn back around, hoping to find a way out, but you come face to face with a broken mirror. It looks very similar to the one in the bathroom of your apartment. It\'s frameless, just a piece of glass hanging on a wall with a green light illuminating behind it.' },
      { type: 'break' },
      { type: 'text', content: 'Wait…\nIs the light behind the mirror in your bathroom green too?\nYou can\'t remember.' },
      { type: 'break' },
      { type: 'text', content: 'You step forward and look at the broken one more closely. When you do you realize the reflection is wrong. It\'s not showing you with a dark concrete wall behind you.' },
      { type: 'break' },
      { type: 'text', content: 'It\'s your apartment.\nYes.\nThere\'s no doubt about it.\nThat\'s definitely the kitchen area just outside the bathroom of your apartment.' },
      { type: 'break' },
      { type: 'text', content: 'But… how?' },
      { type: 'break' },
      { type: 'text', content: 'You look at your reflection and something else catches your eye.\nYou — or the one behind the looking glass — is not quite right. It\'s blurred at the edges like the copy from the hallway. You gasp and take a step back.' },
      { type: 'break' },
      { type: 'text', content: 'Did it see you?\nHow could it not?\nI mean, it\'s looking right at you in the mirror too, right?' },
      { type: 'break' },
      { type: 'text', content: 'You check again for an exit, but there\'s not one. You walk all the way around the mirror and it\'s suspended in air, yet shattered. The room itself is just four concrete walls with no exit. It would be easy for panic to settle in, but you take a deep breath and steady yourself, just like you\'ve always done.' },
      { type: 'break' },
      { type: 'text', content: 'Then you reach out and touch the mirror.\nThe unfinished copy does it at the same time.\nJust before you touch it, a thought crosses your mind. One that terrifies you.\nYou shake it off and press against the broken glass.' },
      { type: 'break' },
      { type: 'text', content: 'And that is when the worst pain you\'ve ever felt hits you.' },
    ],
    prompts: [
      {
        id: 'day4a_q1',
        number: 'I',
        text: 'Describe how your character\'s thoughts evolve during the course of this event — chased by the copy, the lab, the broken mirror, the apartment. How do they process it?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4a_q2',
        number: 'II',
        text: 'What could the notes in their handwriting mean? Are they the one behind all this? Why or why not?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4a_q3',
        number: 'III',
        text: 'What was the thought that crossed their mind just before they touched the broken mirror?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4a_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"What if the mirror is more than a reflection of what I\'m seeing… what if it reflects everything?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day5a',
  },

  {
    id: 'day5a',
    title: 'Day Five: The Fracture',
    path: 'A',
    dayNumber: 5,
    location: {
      place: 'Virescent City',
      level: 'Level ? — Location Unknown',
      time: 'Day ?: Week ?: 3105  ?:??',
    },
    narrative: [
      { type: 'text', content: 'You jolt awake suddenly, covered in a cold sweat.\nYour heart gallops hard against your rib cage and your breathing is erratic.\nWhere are you?' },
      { type: 'break' },
      { type: 'text', content: 'You rub your eyes and try to see, but it\'s too dark.\nWhat time is it?\nWhat a terrible dream…' },
      { type: 'break' },
      { type: 'text', content: 'You laugh into your hands. You\'ve had some crazy dreams before, but that one has to take the cake.\nThen you hear it.\nIt\'s subtle at first, but there\'s no denying it.\nThe three-toned hum of the signal from your dream… or not dream?' },
      { type: 'break' },
      { type: 'text', content: 'You sit up, suddenly feeling very sick to your stomach. What\'s happening? Why is it so dark? You call out for The Net to turn the lights on, but no reply comes and no lights.' },
      { type: 'break' },
      { type: 'text', content: 'You try to flick your wrist to check the time on your comm, but nothing happens. You tap the screen to wake it… well, you try to, but you only touch your arm.' },
      { type: 'break' },
      { type: 'text', content: 'Your comm is gone.\nThose are supposed to be permanent.\nYou don\'t remember a time that you didn\'t have it on your arm. It\'s always been there, right?' },
      { type: 'break' },
      { type: 'text', content: 'You try to think back to your earliest memory, but your mind is too fuzzy. You can\'t call up anything from your childhood — just that terrifying memory that\'s not your own.' },
      {
        type: 'echo',
        journalKey: 'char.strangeMemory',
        prefix: 'There it is again: ',
        suffix: ' — that memory that belongs to no life you can recall living.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'Frustrated, you stand up and walk with your arms out trying to find the wall. After a few steps you reach it and feel around wildly until you hit a light switch, which you turn on.' },
      { type: 'break' },
      { type: 'text', content: 'The sudden burst of light is blinding and you close your eyes instinctively. A pain sears into your head and you rub your temples. Another wave of nausea passes and you finally feel like you might be able to open your eyes again.' },
      { type: 'break' },
      { type: 'text', content: 'You do.\nThen blink.\nThe room is out of focus, but you think it\'s your bedroom.\nYou blink again and shade your eyes from the light.' },
      { type: 'break' },
      { type: 'text', content: 'Yes… this is your room.\nBut, it\'s not at the same time.' },
      { type: 'break' },
      { type: 'text', content: 'You\'ve never had sheets that color — almost luminescent green. Or is that the light? You\'re so disoriented you can\'t tell the difference. Cold air blows against your skin and you realize you\'re naked. You never sleep naked. What in the world is happening?' },
      { type: 'break' },
      { type: 'text', content: 'You go to the closet and pull on an outfit. It doesn\'t matter which one — they\'re all the same. The protection from the cool air feels good, though the fabric feels off, like it was hung dry instead of using standard methods.' },
      { type: 'break' },
      { type: 'text', content: 'Oh well, that doesn\'t matter anyway. You head out of the bedroom into the main living area. For a second you had doubted whether this was your apartment, but now you\'re certain. That\'s definitely your couch and end table. The kitchen looks right.' },
      { type: 'break' },
      { type: 'text', content: 'You glance out the window at the city.\nView seems right… you think.' },
      { type: 'break' },
      { type: 'text', content: 'Then doubt starts to creep back in, but you shove it away and turn quickly from the window.\nYou head to the bathroom and relieve yourself before washing your hands. The water is ice cold, so you splash some on your face to help center you. It works. You certainly feel much better.' },
      { type: 'break' },
      { type: 'text', content: 'You dry your face and hands on the towel hanging beside the mirror.' },
      { type: 'break' },
      { type: 'text', content: 'The mirror.' },
      { type: 'break' },
      { type: 'text', content: 'You\'re suddenly afraid to look.\nYou know it\'s silly.\nIt was just a dream.\nBut something at the back of your mind is tugging on you.' },
      { type: 'break' },
      { type: 'text', content: 'You pull the towel down slowly and give it a look.\nYour stomach drops.\nYour heart skips a beat.' },
      { type: 'break' },
      { type: 'text', content: 'The mirror is shattered.\nJust like the dream.' },
      { type: 'break' },
      { type: 'text', content: 'No\nNo\nNo\nNO\nNO\nNO, NO, NO, NO, NO!' },
      { type: 'break' },
      { type: 'text', content: 'You back away and slam the door shut, breathing hard. This can\'t be. It\'s not real. It can\'t be real.' },
      { type: 'break' },
      { type: 'text', content: 'You feel like you\'re going crazy. Maybe you are crazy. Maybe the world is falling apart. Something is definitely fractured.' },
      { type: 'break' },
      { type: 'text', content: 'Then you feel it.\nThe sudden urge to leave.\nTo get out of the apartment as fast as possible.' },
      { type: 'break' },
      { type: 'text', content: 'You don\'t know where you\'ll go.\nDoesn\'t matter.\nAll that does is getting out of here and clearing your head.' },
      { type: 'break' },
      { type: 'text', content: 'Without thinking you head out the front door and into the elevator. A few minutes later you\'re standing outside your apartment building and looking down the street. It must be late — there\'s no one else around.' },
      { type: 'break' },
      { type: 'text', content: 'Weird.\nThis city never sleeps.' },
      { type: 'break' },
      { type: 'text', content: 'You start walking in one direction and change your mind. Something didn\'t feel right about that. After a few blocks you take a quick turn at an intersection and run headfirst into someone.' },
      { type: 'break' },
      { type: 'text', content: 'You\'d normally apologize, but you can\'t be bothered.\nYou look up at the person to see if they\'re alright and you stop short.' },
      { type: 'break' },
      { type: 'text', content: 'It\'s you.\nNo, not you… but you.\nA copy of you.\nThe one from down below?' },
      { type: 'break' },
      { type: 'text', content: 'It doesn\'t look quite right. Maybe it\'s your eyes playing with you, but it seems erratic and slightly off kilter.' },
      { type: 'break' },
      { type: 'text', content: 'But it\'s definitely you.' },
      { type: 'break' },
      { type: 'text', content: 'You tilt your head and mumble "hmmm" under your breath.\nIt does the same.' },
      { type: 'break' },
      { type: 'text', content: 'You grab the keepsake you always have on you.\nIt does the same.' },
      { type: 'break' },
      { type: 'text', content: 'Anger surges through you.\nThis isn\'t fair. It\'s not right. It\'s not real.\nThe copy points at you and tries to speak, but nothing happens… except the faint sound of metal clicking against metal. It\'s odd, but you think it\'s the same tempo as the hum from the signal.' },
      { type: 'break' },
      { type: 'text', content: 'You point back at it and yell for it to stop. It looks at you with confusion, then fear, then sadness?' },
      { type: 'break' },
      { type: 'text', content: 'That\'s it.\nYou\'ve had enough.\nYou\'re tired of playing this stupid game.' },
      { type: 'break' },
      { type: 'text', content: 'So you reach out and grab it by the arm.' },
      { type: 'break' },
      { type: 'text', content: 'And the city screams in agony.' },
    ],
    prompts: [
      {
        id: 'day5a_q1',
        number: 'I',
        text: 'What makes the false memory so terrifying for your character? Why do you think it is happening?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5a_q2',
        number: 'II',
        text: 'What are the implications of the apartment being partially wrong?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5a_q3',
        number: 'III',
        text: 'Describe the moment the city begins to scream in agony. What are the following moments like?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5a_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"Fractured. The whole city is fractured. I\'m fractured. We\'re all fractured… but what does it all mean?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day6a',
  },

  {
    id: 'day6a',
    title: 'Day Six: The Choice',
    path: 'A',
    dayNumber: 6,
    location: {
      place: 'Virescent City',
      level: 'Level 10 — Residential District',
      time: 'Day Six: Week 49: 3105  04:21',
    },
    narrative: [
      { type: 'text', content: 'You look down at the time on your comm.\nThank the gods you found it. It still doesn\'t sit on your wrist exactly right, since you had to create a makeshift clasp for the broken titanium. Regardless, it feels good to have it back on. At least something is how it should be.' },
      { type: 'break' },
      { type: 'text', content: 'How you\'ve lost so much time, you\'ll never know.\nDays have gone by.' },
      { type: 'break' },
      { type: 'text', content: 'Days.' },
      { type: 'break' },
      { type: 'text', content: 'You shake your head, which thuds with the dull headache you\'ve had since you touched the copy of yourself. It\'s not enough to take pain killers, but it\'s definitely annoying. You rub your temples for a moment and take a deep breath.' },
      { type: 'break' },
      { type: 'text', content: 'The sound of the city screaming haunts your memory.\nYou\'ve never heard something so shrill.\nSo pained.\nSo violent.' },
      { type: 'break' },
      { type: 'text', content: 'It slammed into your chest like a ton of bricks and resonated through your entire being.' },
      { type: 'break' },
      { type: 'text', content: 'You have no clue how long it lasted.\nSeconds?\nMinutes?\nHours?\nDays…?' },
      { type: 'break' },
      { type: 'text', content: 'You just know that the pain the city felt was suddenly your own.\nLike the two were becoming one…\nOr perhaps like a symbiotic relationship gone wrong.' },
      { type: 'break' },
      { type: 'text', content: 'It was like you bit the host and it fought back.' },
      { type: 'break' },
      { type: 'text', content: 'The billboards and screens have been black since that moment.\nNo more ads.\nNo propaganda.\nNo secret messages targeted at you.' },
      { type: 'break' },
      { type: 'text', content: 'Just silence.\nAwful silence.' },
      { type: 'break' },
      { type: 'text', content: 'You\'ve wandered the streets of levels 10 and 11 aimlessly, looking for another soul.\nAny sign of life.\nBut you\'re alone.' },
      { type: 'break' },
      { type: 'text', content: 'Where there used to be clinics and shops and small cafès there are now concrete walls.\nNo doors.\nNo windows.\nNothing but an industrial wasteland as far as the eye can see.' },
      { type: 'break' },
      { type: 'text', content: 'The only exception is your apartment building, which you can still access.\nThough, even that isn\'t right.\nYou live on the thirteenth floor, but all the other floors are blank corridors.\nConcrete walls without doors.\nJust like outside.' },
      { type: 'break' },
      { type: 'text', content: 'Has the entire city glitched out?\nHave you?' },
      { type: 'break' },
      { type: 'text', content: 'You press hard against your forehead, as it starts pounding again.\nWhy can\'t you remember the things you want to remember?' },
      { type: 'break' },
      { type: 'text', content: 'Your parents.\nYour childhood.\nYour partner.\nYour favorite foods and holidays.' },
      {
        type: 'echo',
        journalKey: 'char.hiddenFear',
        prefix: 'And beneath all of it — that thing you\'ve always avoided acknowledging — ',
        suffix: ' — it\'s the clearest thought you have. That scares you most of all.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'They\'re all…\nStatic.' },
      { type: 'break' },
      { type: 'text', content: 'Whatever. At the moment, what matters is finding a way to end this terrible nightmare. To either wake up and go about your normal life or fix what\'s broken. Which to decide? That\'s the question.' },
      { type: 'break' },
      { type: 'text', content: 'And speaking of decisions, you\'ve been thinking.\nReally. Thinking.' },
      { type: 'break' },
      { type: 'text', content: 'And the thought scares the hell out of you, but you can\'t shake it.\nIt\'s there, ever present.\nNagging at the back of your mind like a dripping faucet.\nLike an annoying younger sibling.\nWearing you down bit by bit until you\'ll have no choice but to face the music and make a decision.' },
      { type: 'break' },
      { type: 'text', content: 'What if the things you\'ve seen —\nThe copies, below and above.\nWhat if they\'re not copies after all.' },
      { type: 'break' },
      { type: 'text', content: 'What if… you\'re the copy?' },
      { type: 'break' },
      { type: 'text', content: 'NO.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s not possible.\nYou know that you are the real version.\nThe one they copied.' },
      { type: 'break' },
      { type: 'text', content: 'Right?…\nDon\'t you?' },
      { type: 'break' },
      { type: 'text', content: 'That\'s when your comm buzzes.\nA new message.\nYou question whether it\'s worth reading or not.\nProbably going to disappear anyway.' },
      { type: 'comm', content: '"Can you feel that?\nWe know you can.\nThe weight of it all.\nIt\'s real.\nIt\'s heavy.\nIt\'s on you.\nYou must decide…\nWe are waiting below."' },
      { type: 'break' },
      { type: 'text', content: 'Warmth climbs your esophagus, like fire from your belly. It burns in your chest and makes your face feel flush. How dare they — whoever the hell "they" are. How dare they play games with you. Like you\'re some puppet in their theatre.' },
      { type: 'break' },
      { type: 'text', content: 'You look at the screen again.\nYep.\nJust like you thought — the message is gone.' },
      { type: 'break' },
      { type: 'text', content: 'Your comm buzzes again.\n"Make your choice. We\'re waiting below."' },
      { type: 'break' },
      { type: 'text', content: 'What choice?\nThere are so many choices.' },
      { type: 'break' },
      { type: 'text', content: 'But you know. Deep inside you know what the choice is. Your gut has been telling you all along. You\'ve known since that morning when the city felt off. You\'ve known since you left your apartment and decided to chase the proximity alert rather than ignore it. You\'ve known since you first laid eyes on that…' },
      { type: 'break' },
      { type: 'text', content: 'Thing.\nAbomination?\nOther you.' },
      { type: 'break' },
      { type: 'text', content: 'You must choose what to believe.\nYou\'re the only one who can.' },
    ],
    prompts: [
      {
        id: 'day6a_q1',
        number: 'I',
        text: 'Begin by journaling through some of the questions your character has been asking themselves. What emotions and thoughts have risen due to those questions?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6a_q2',
        number: 'II',
        text: 'Write out the thought process that leads up to their decision. What does your character believe about: the city and the glitching? The messages and who\'s sending them? Themselves — are they the original or a copy? Reality itself?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6a_q3',
        number: 'III',
        text: 'Once their decisions are made, one more remains. What are they going to do?\n\n  1. Go below and face whoever is sending the messages.\n  2. Try to communicate with them otherwise.\n  3. Find a way to end the entire experience.\n\nHow does this choice make them feel? What are the first steps?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6a_q4',
        number: 'IV',
        text: 'How does the false memory tie to the incident? Does this help ground your character in their choices, or make them more difficult?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6a_q5',
        number: 'V',
        text: 'End your entry with this line:',
        endingPrefix: '"The choice wasn\'t easy, but what\'s done is done… Now, it\'s time to face the truth."',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day7',
  },
]
