// Path B: The Missing — Days 2 through 6

export const pathBScenes = [
  {
    id: 'day2b',
    title: 'Day Two: The Missing',
    path: 'B',
    dayNumber: 2,
    location: {
      place: 'Virescent City',
      level: 'Level 10 — Residential District',
      time: 'Day One: Week 49: 3105  09:32',
    },
    narrative: [
      { type: 'text', content: 'You decide not to take the stairwell.' },
      { type: 'break' },
      { type: 'text', content: 'Maybe it\'s fear.\nMaybe it\'s just instinct.\nMaybe it\'s that rational part of your mind screaming that nothing good ever comes from chasing fantasies and falling down rabbit holes.' },
      { type: 'break' },
      { type: 'text', content: 'Or maybe… just maybe, you want to find answers on your own terms.' },
      { type: 'break' },
      { type: 'text', content: 'You turn away from the stairwell and force the signal to fade into the background hum of the city. You\'ll focus on it again later. Now it\'s a distraction.' },
      { type: 'break' },
      { type: 'text', content: 'You turn your focus to what\'s really important in the moment.' },
      { type: 'break' },
      { type: 'text', content: 'The drone.\nThe street vendor.\nThe glitching billboard.' },
      { type: 'break' },
      { type: 'text', content: 'It hardly matters which one you choose, because in that very moment the world decided to shift around you.' },
      { type: 'break' },
      { type: 'text', content: 'You step forward and the air bends.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s not normal.\nThe air doesn\'t normally bend for you.' },
      { type: 'break' },
      { type: 'text', content: 'For a split second, the pedestrians around you smear at the edges like a corrupted frame on a holo feed. Light drags behind them in ghostly streaks. Their movements glitch, skip, repeat.' },
      { type: 'break' },
      { type: 'text', content: 'You blink.\nAgain.\nThen everything snaps back into place.' },
      { type: 'break' },
      { type: 'text', content: 'Everything except for one person.' },
      { type: 'break' },
      { type: 'text', content: 'Someone who was standing directly in your line of sight just seconds ago is now gone.\nNot "walked away" gone.\nNot "turned the corner while you blinked" gone.' },
      { type: 'break' },
      { type: 'text', content: 'Gone, as in dematerialized gone.' },
      { type: 'break' },
      { type: 'text', content: 'You remember them clearly.\nThe color of their coat.\nThe smell of their cologne or perfume.\nThe tilt of their head as they read something.\nThe way they shifted their weight while walking.\nThe small bag they had slung over their shoulder.' },
      { type: 'break' },
      { type: 'text', content: 'But now…' },
      { type: 'break' },
      { type: 'text', content: 'Nothing occupies that spot.\nNothing except the faint impression that the world is trying very hard to pretend that person never existed.' },
      { type: 'break' },
      { type: 'text', content: 'People walk around the void without acknowledging it.\nOddly, they step around it rather than through it.\nIt\'s like their subconscious minds are avoiding the thing they can\'t see — but you know what it is.' },
      { type: 'break' },
      { type: 'text', content: 'Or what it was, rather.' },
      { type: 'break' },
      { type: 'text', content: 'A cold chill climbs your spine.\nYour head hurts.\nYour chest tightens.\nBreathing is suddenly much more difficult.' },
      { type: 'break' },
      { type: 'text', content: 'Then your comm vibrates.\nOnce, but hard.' },
      { type: 'break' },
      { type: 'text', content: 'You look up.' },
      { type: 'break' },
      { type: 'text', content: 'Every megascreen around you flickers to black in perfect unison —\nJust for a fraction of a second.' },
      { type: 'break' },
      { type: 'text', content: 'When the ads return, the slogans are gone.\nThe imagery is gone.\nAll that\'s left is a black screen with bright white text.' },
      { type: 'break' },
      { type: 'text', content: 'One phrase repeated across the skyline:' },
      { type: 'comm', content: '"LEVEL 0: ENTRY COMPROMISED"' },
      { type: 'break' },
      { type: 'text', content: 'You swallow hard against the lump in your throat.\nYour heart threatens to hammer out of your chest.' },
      { type: 'break' },
      { type: 'text', content: 'The city isn\'t malfunctioning.\nIt\'s not glitching.\nThis isn\'t an accident.' },
      { type: 'break' },
      { type: 'text', content: 'Something is signaling you.' },
      { type: 'break' },
      { type: 'text', content: 'And whatever vanished from the street right next to you must be connected.' },
      { type: 'break' },
      { type: 'text', content: 'Connected to the message from this morning.\nConnected to this message now.\nConnected to that damned stairwell.\nConnected to whatever is happening beneath your feet.' },
      { type: 'break' },
      { type: 'text', content: 'You\'re not alone.\nYou\'re not imagining things.\nAnd you\'re definitely not in control.' },
      { type: 'break' },
      { type: 'text', content: 'You take a slow step back.\nThe empty space where the person once stood stretches in your vision.\nImpossibly wide.\nLike a hole in the fabric of reality, just for a moment.' },
      { type: 'break' },
      { type: 'text', content: 'Then it snaps back.\nIt\'s a normal patch of sidewalk.\nExcept you know that\'s not right.' },
      { type: 'break' },
      { type: 'text', content: 'Something is missing.\nA person is missing.' },
      { type: 'break' },
      { type: 'text', content: 'If one is missing…\nThen more could be.\nMost definitely are.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s when your comm explodes with messages — so fast your vision blurs trying to track them:' },
      { type: 'comm', content: '"WE KNOW THAT YOU KNOW"\n"WE ARE DOWN BELOW"\n"WE KNOW THAT YOU KNOW"\n"COME MEET US DOWN BELOW"\n"WE KNOW THAT YOU KNOW"\n"WE ARE WAITING DOWN BELOW"\n"WE KNOW THAT YOU KNOW"\n"WE\'LL SEE YOU DOWN BELOW"' },
    ],
    prompts: [
      {
        id: 'day2b_q1',
        number: 'I',
        text: 'Describe the missing person. The details you recall matter more than accuracy. Why does this person stand out from everyone in the crowd?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day2b_q2',
        number: 'II',
        text: 'How does your character react emotionally to witnessing a disappearance that no one else notices? Focus on sensations: cold, heat, dizziness, heartbeat, breath, smells.',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day2b_q3',
        number: 'III',
        text: 'Choose one follow-up anomaly and describe the moment as if it unfolds slowly — perhaps too slowly:',
        isAnomalyChoice: true,
        choices: [
          'A nearby screen briefly shows your face — older or mangled',
          'A drone hovers close and emits the three-tone signal you had tried to push from your mind',
          'A stranger bumps into you and whispers, "Whatever you do, don\'t go down below."',
          'The missing person\'s bag appears at your feet',
          'Your shadow splits into two before merging again',
        ],
      },
      {
        id: 'day2b_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"If they vanished above ground… what happens below?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day3b',
  },

  {
    id: 'day3b',
    title: 'Day Three: The Symmetry Above',
    path: 'B',
    dayNumber: 3,
    location: {
      place: 'Virescent City',
      level: 'Level 10 — Residential District',
      time: 'Day Two: Week 49: 3105  02:22',
    },
    narrative: [
      { type: 'text', content: 'Reeled from the blast of messages from this unknown force or entity, you blink and rub your eyes. What in the world is happening? Could this day get any stranger?' },
      { type: 'break' },
      { type: 'text', content: 'You look at your comm again.\nYou want to re-read the message sequence to see if anything sticks out to you about it.\nBut you can\'t.' },
      { type: 'break' },
      { type: 'text', content: 'It\'s gone.\nWiped itself, just like before.' },
      { type: 'break' },
      { type: 'text', content: 'What does catch your eye however is the time.\n2:22 AM\nThat\'s impossible. It was just nine in the morning wasn\'t it?\nYou\'re certain that it was. You were on your way to work and got distracted by this anomaly, by the signal, by… whatever the hell is going on.' },
      { type: 'break' },
      { type: 'text', content: 'You look up and scan your surroundings.\nThe comm is glitching.\nIt has to be.' },
      { type: 'break' },
      { type: 'text', content: 'Except…' },
      { type: 'break' },
      { type: 'text', content: 'The streets are empty.' },
      { type: 'break' },
      { type: 'text', content: 'Mere seconds ago there were hundreds of people walking in all directions of the junction, but now not a soul. You feel a tingle crawl up your spine like ice. This can\'t be… can it?' },
      { type: 'break' },
      { type: 'text', content: 'You take a deep breath in and try to steady yourself. A comm laying on the sidewalk catches your eye.\nPrecisely where you saw the person disappear.\nIs it theirs?\nHas to be right?' },
      { type: 'break' },
      { type: 'text', content: 'You bend down and pick it up to examine it.\nIts display is busted and glitching.\nThe titanium band shorn in two like a laser cut through it.\nIt\'s almost uncomfortable to hold — it\'s so hot.' },
      { type: 'break' },
      { type: 'text', content: 'You turn it over and look at the nameplate, which is melted. The only remaining letters are the last two of the last name — "ns."' },
      { type: 'break' },
      { type: 'text', content: 'Your breath catches.\nYour heart stammers in your chest.\nIt can\'t be…' },
      {
        type: 'echo',
        journalKey: 'char.incident',
        prefix: 'The incident floods back in an instant — ',
        suffix: ' — and suddenly those two letters feel like an accusation.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'Your comm buzzes on your wrist, causing you to jump.' },
      { type: 'comm', content: 'HIGH HEART RATE WARNING\nPLEASE FIND A PLACE TO SIT AND TAKE THREE DEEP BREATHS\nFAILURE TO COMPLY WILL RESULT IN EMERGENCY SERVICES BEING DISPATCHED' },
      { type: 'break' },
      { type: 'text', content: 'You comply and sit on the sidewalk, taking three deep breaths. After a moment your comm dings, satisfied you\'re not dying.\nNot yet, anyway.' },
      { type: 'break' },
      { type: 'text', content: 'You stand up and decide to head back to your apartment to get some sleep.\nPerhaps this is all a crazy dream and you\'ll wake up any moment.\nYou walk to the end of the block and stop dead in your tracks.' },
      { type: 'break' },
      { type: 'text', content: 'You nearly ran into someone as you came up to the street corner. Nothing too out of the ordinary there, it is a megacity after all. One that never sleeps. But this isn\'t just a random stranger.' },
      { type: 'break' },
      { type: 'text', content: 'No.\nIt\'s you.' },
      { type: 'break' },
      { type: 'text', content: 'Standing just beyond arms reach is a perfect copy of you.\nWell, nearly perfect.' },
      { type: 'break' },
      { type: 'text', content: 'Every detail, down to the random scar from childhood is present, but the face looks… off.\nYou squint and realize that the edges of the face are smeared, ever so slightly.\nJust like the people on the street earlier when everything glitched around you.' },
      { type: 'break' },
      { type: 'text', content: 'You tilt your head and mutter a "hmm" under your breath.\nIt does the same.' },
      { type: 'break' },
      { type: 'text', content: 'You jump from fright, not expecting it to mimic you.\nIt does the same.' },
      { type: 'break' },
      { type: 'text', content: 'You instinctively reach up and grab the keepsake your mother gave you.\nIt does the same.' },
      { type: 'break' },
      { type: 'text', content: 'You shout at it to stop, and it opens its mouth wide, like it\'s trying to shout back. But the only thing that comes out is a faint clicking sound. Metal on metal. Otherworldly.' },
      { type: 'break' },
      { type: 'text', content: 'Your skin crawls.\nYour heartbeat thuds in your ears.\nYou feel your stomach turn and threaten to send the last thing you ate back up the hatch.' },
      { type: 'break' },
      { type: 'text', content: 'Suddenly it raises its right hand and points directly at you with an angry look in its eyes.' },
      { type: 'break' },
      { type: 'text', content: '"STOP IT!"' },
      { type: 'break' },
      { type: 'text', content: 'Your own voice shouting at you, just like you did a moment ago… except, the voice didn\'t come from the copy.\nIt came from behind you.' },
      { type: 'break' },
      { type: 'text', content: 'Fear surges in your chest and your comm starts buzzing wildly again.' },
      { type: 'break' },
      { type: 'text', content: 'And that\'s when the false you grabs your arm.' },
    ],
    prompts: [
      {
        id: 'day3b_q1',
        number: 'I',
        text: 'Journal about the precise moment that your character realized a time-shift had taken place.',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day3b_q2',
        number: 'II',
        text: 'How did it feel to run into a double on that dark street corner? What alternative explanations began running through your head?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day3b_q3',
        number: 'III',
        text: 'Choose one follow-up anomaly and describe how all five senses are involved in processing this realization:',
        isAnomalyChoice: true,
        choices: [
          'Your comm gives you a warning that makes no sense',
          'The billboards all around match the message from your comm about high heart rate',
          'The city lights flicker in perfect sync with your heartbeat',
          'The copy begins speaking in your voice, but words you did not say',
          'The streets are suddenly filled with people again, but they all look like you',
        ],
      },
      {
        id: 'day3b_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"If there\'s another me walking around the streets… could there be others?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day4b',
  },

  {
    id: 'day4b',
    title: 'Day Four: The Hunted',
    path: 'B',
    dayNumber: 4,
    location: {
      place: 'Virescent City',
      level: 'Level ? — Location Unknown',
      time: 'Day Three: Week 49: 3105  07:17',
    },
    narrative: [
      { type: 'text', content: 'Cold air blows across the back of your neck. You slowly wake from your slumber, lifting your head off your very numb hands. You\'re sitting in a firm chair and have your arms crossed on the cold metal table. You try to wipe the drool from the corners of your mouth, but your fingers are too tingly to do it well.' },
      { type: 'break' },
      { type: 'text', content: 'You wonder where you are.\nThen you laugh.\nThat was one crazy dream.\nThank goodness that\'s over.' },
      { type: 'break' },
      { type: 'text', content: 'Your eyes begin to adjust to your surroundings and you\'re confused. This isn\'t your apartment.\nIt\'s not work either.\nThis is someplace you\'ve never seen before.' },
      { type: 'break' },
      { type: 'text', content: 'You jump up and spin around, fully taking the room in and feeling wide awake suddenly. You\'re in a small room with several metal tables that have lab equipment spread about. There are lab coats hanging on a hook on the far wall, right next to a glass cabinet full of supplies. There\'s a large table to your left that has a large circular light above it, which is illuminating the room in an odd green hue.' },
      { type: 'break' },
      { type: 'text', content: 'You rub your eyes.\nHow did you get here?' },
      { type: 'break' },
      { type: 'text', content: 'You inspect the examination table further and realize there are restraints welded to the side.\nYou touch the one closest to you.\nIt\'s still warm, like it was used…\nVery recently.' },
      { type: 'break' },
      { type: 'text', content: 'You quickly withdraw your hand and look at the table you were just sleeping at. There are pages scattered everywhere with your handwriting on them. You pick one up that has a few blocks of text, but one sentence is circled wildly in blue ink.' },
      { type: 'comm', content: 'THE PATIENT DOESN\'T REMEMBER THE PROCEDURE' },
      { type: 'break' },
      { type: 'text', content: 'You stare at the page for a long time. The rest of the text doesn\'t make any sense, but it\'s definitely your handwriting.' },
      { type: 'break' },
      { type: 'text', content: 'You look down at yourself.\nYou\'re wearing a lab coat over your normal clothes. In the chest pocket is a blue pen.' },
      { type: 'break' },
      { type: 'text', content: 'You throw the paper down and grab the sides of your head. What is this? Some kind of sick joke? Did someone drug you? Did they wipe your memory?' },
      { type: 'break' },
      { type: 'text', content: 'You rip the lab coat off of your body and throw it across the room. You want nothing to do with it. You\'re not a scientist running sick experiments on patients who can\'t remember what you\'ve done…' },
      { type: 'break' },
      { type: 'text', content: 'Right?\nThat\'s not you, is it?\nWhy is it so hard to remember things!?\nWhy is your brain so full of static?' },
      { type: 'break' },
      { type: 'text', content: 'You sit down to think — to really think — about the last thing you remember. Yesterday you had that weird feeling in the apartment, like the city was wrong. Then the signal disturbance on the way to work, which you followed. The glitching billboards, the disappearing person, the…' },
      { type: 'break' },
      { type: 'text', content: 'Other you.' },
      { type: 'break' },
      { type: 'text', content: 'Didn\'t it grab you?\nIt did, right?\nGrabbed you by the arm.\nYes, that\'s right.\nIt definitely did…' },
      { type: 'break' },
      { type: 'text', content: 'But that doesn\'t explain how you got here. It doesn\'t explain anything. It just leaves more questions.' },
      { type: 'break' },
      { type: 'text', content: 'You come to yourself and realize you\'re sitting down at the table, holding the pen and have just written pages of notes.' },
      { type: 'break' },
      { type: 'text', content: 'But they aren\'t what you were just thinking about.\nThey\'re… something else.\nGraphs and words you don\'t recognize are covering the page.\nIt\'s in your language, but it might as well be written in a foreign language.' },
      { type: 'break' },
      { type: 'text', content: 'You stand up and throw the pen down, then back away from the table.\nYour skin feels like it\'s crawling and your chest is tight.' },
      { type: 'break' },
      { type: 'text', content: 'What\'s happening?\nWhat is actually happening?' },
      { type: 'break' },
      { type: 'text', content: 'Your comm buzzes violently on your wrist and you jump.\nWorst timing ever.\nYou flick your wrist and read the message, but it takes you a moment to process what it says.' },
      { type: 'comm', content: '"Go through the door."' },
      { type: 'break' },
      { type: 'text', content: 'You look around the room.\nThere is no door.\nOh gods… there\'s no door.\nHow do you get out of here?' },
      { type: 'break' },
      { type: 'text', content: 'A second notification comes:' },
      { type: 'comm', content: '"Door. Now."' },
      { type: 'break' },
      { type: 'text', content: 'You watch the message wipe from the screen and look up to find a door slightly ajar directly in front of you, maybe ten paces away.' },
      { type: 'break' },
      { type: 'text', content: 'Impossible.\nCan\'t be.\nThat wasn\'t there a moment ago…' },
      { type: 'break' },
      { type: 'text', content: 'But it\'s there now. You can\'t help yourself and you dash over to it. It\'s a way out and as far as you can tell, it\'s the only one.' },
      { type: 'break' },
      { type: 'text', content: 'You push it open and find yourself in…\nAn empty corridor?' },
      { type: 'break' },
      { type: 'text', content: 'It\'s long and narrow, dimly lit by some lights in the corner of the floor and concrete walls. The air is cold and stale.' },
      { type: 'break' },
      { type: 'text', content: '"Hello?" you say aloud.\nNothing.\nYour voice is swallowed up.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s odd. You take a step into the corridor and your footsteps are completely muted as well. You stomp your feet on the floor, but nothing happens except a slight pain in the balls of your feet.' },
      { type: 'break' },
      { type: 'text', content: 'You walk to the end of the corridor, but there\'s literally nothing else there. It\'s void of any hallways, stairs, doors, windows… anything.' },
      { type: 'break' },
      { type: 'text', content: 'Disappointed, you turn and decide to go back the way you came. At least that room had something to do.' },
      { type: 'break' },
      { type: 'text', content: 'Except, you can\'t.\nThe door is gone.' },
      { type: 'break' },
      { type: 'text', content: 'You run up to that end of the hall and pound the wall, but nothing happens. The door has completely sealed shut and you can\'t even tell there was one.' },
      { type: 'break' },
      { type: 'text', content: 'After a few moments you turn your back to the door and sigh.\nWhy do these things keep happening to you?' },
      { type: 'break' },
      { type: 'text', content: 'And that\'s when you see it.\nThe copy.\nThe false you.' },
      { type: 'break' },
      { type: 'text', content: 'It walks into the corridor from the side about halfway between you and the other end of the hall. At first you\'re so shocked you don\'t move. Then you raise your flashlight and it does the same. You tilt your head. So does the copy.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s it.\nYou\'ve had enough.' },
      { type: 'break' },
      { type: 'text', content: 'Without thinking, you sprint for it.\nIf someone wants to clone you or create some elaborate mind game, you\'re going to retaliate.' },
      { type: 'break' },
      { type: 'text', content: 'They realize too late what\'s happening — you see that in their eyes.\nYou dive to tackle them…' },
      { type: 'break' },
      { type: 'text', content: 'And miss.' },
      { type: 'break' },
      { type: 'text', content: 'You hit the concrete floor hard and skid to a stop a few feet later. Anger rages inside you like a caged lion.\nThe copy is running towards the door.' },
      { type: 'break' },
      { type: 'text', content: 'The door?\nThe door!' },
      { type: 'break' },
      { type: 'text', content: 'It\'s back.\nAnd the false you is going to get there first.' },
      { type: 'break' },
      { type: 'text', content: 'You scramble to your feet and try to beat them there, but it\'s no use. Just as it flings itself into the room, the door slams shut in your face.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s when your comm buzzes once.' },
      { type: 'comm', content: '"Fractured. All will be fractured."' },
    ],
    prompts: [
      {
        id: 'day4b_q1',
        number: 'I',
        text: 'Going off appearances, it seems that your character is responsible for what has taken place in this laboratory. Do you believe they are or not? Explain your reasoning in a self-reflection journal entry from their perspective.',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4b_q2',
        number: 'II',
        text: 'These comm messages seem to come at both convenient and inconvenient times. Who does your character think is sending them? Why do they think that?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4b_q3',
        number: 'III',
        text: 'Describe what thoughts go through your character\'s mind when they read the final message that all will be fractured.',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day4b_q4',
        number: 'IV',
        text: 'End your entry with this line:',
        endingPrefix: '"Everything I know is falling apart… who am I, anyway?"',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day5b',
  },

  {
    id: 'day5b',
    title: 'Day Five: The Fracture',
    path: 'B',
    dayNumber: 5,
    location: {
      place: 'Virescent City',
      level: 'Level ? — Location Unknown',
      time: 'Day ?: Week ?: 3105  ?:??',
    },
    narrative: [
      { type: 'text', content: 'You stand with your back to what used to be a door into a lab.\nYou\'re slightly out of breath, but getting it under control.\nYou look down at your comm and try to check the time, but it\'s apparently disconnected from The Net.' },
      { type: 'break' },
      { type: 'text', content: 'It said "all will be fractured."\nWhat does that even mean?' },
      { type: 'break' },
      { type: 'text', content: 'You shake your head and decide that waiting here in this dimly lit hallway won\'t accomplish anything, so you head towards the spot you think you saw the copy enter from. You\'re a bit surprised to find an opening in the wall. That definitely wasn\'t there before.' },
      { type: 'break' },
      { type: 'text', content: 'You peer into the darkness.\nToo dark to see anything.\nYou shine your flashlight into the opening and realize it\'s a stairwell.\nA long one.\nVery. Long.' },
      { type: 'break' },
      { type: 'text', content: 'As far as the light carries, the stairs go up. You consider how badly your legs are going to hurt climbing it, but anything is better than standing around an empty hallway and starving to death.' },
      { type: 'break' },
      { type: 'text', content: 'Or worse.' },
      { type: 'break' },
      { type: 'text', content: 'So you begin the climb.\nAt first it\'s not too terrible. The air is cold and while you know that\'ll be uncomfortable for a few minutes, you\'ll be thankful soon enough.' },
      { type: 'break' },
      { type: 'text', content: 'And so you climb.\nAnd climb.\nAnd climb.' },
      { type: 'break' },
      { type: 'text', content: 'After what feels like an hour straight of climbing, you stop to catch your breath. Sweat is beading up and rolling down your back. Your quads are screaming in pain.' },
      { type: 'break' },
      { type: 'text', content: 'You look back down the stairwell and see…\nNothing.\nJust a black void.' },
      { type: 'break' },
      { type: 'text', content: 'You mutter something under your breath about how terrible of a day it\'s been, and then you see it.' },
      { type: 'break' },
      { type: 'text', content: 'Up ahead, in the distance.\nA faint glow on the left.\nThe wall?\nMost likely.' },
      { type: 'break' },
      { type: 'text', content: 'So you climb again. This time making each step deliberate and heading towards the goal of checking out whatever that light source is.' },
      { type: 'break' },
      { type: 'text', content: 'Your mind races through possibilities.\nMaybe it\'s a corridor and that\'s the light coming under the door.\nMaybe it\'s a landing to one of the lower levels.\nMaybe it\'s…' },
      { type: 'break' },
      { type: 'text', content: 'You shake that thought off and just climb. No use digging into painful memories.' },
      {
        type: 'echo',
        journalKey: 'char.strangeMemory',
        prefix: 'But it\'s already there — ',
        suffix: ' — it fills the silence of the stairwell like a ghost.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'Oddly, the glow doesn\'t get any brighter the closer you get to it.\nNo, it stays precisely the same.' },
      { type: 'break' },
      { type: 'text', content: 'And when you come upon it, you see why.\nOn the left hand wall, directly in the concrete, is a miniscule crack.\nThe tiniest bit of luminescence is filtering through it — a sickly green color.\nIt\'s pulsing to the rhythm of the sound you\'ve been hearing since this all started.' },
      { type: 'break' },
      { type: 'text', content: 'Fractured.\nAll will be fractured.' },
      { type: 'break' },
      { type: 'text', content: 'That\'s what it said.\nYou\'re sure of it.' },
      { type: 'break' },
      { type: 'text', content: 'And here you are, staring at a crack in the wall. A fracture in the foundation of the city itself. Pulsing with the pained hum of…' },
      { type: 'break' },
      { type: 'text', content: 'Well, you don\'t know really.' },
      { type: 'break' },
      { type: 'text', content: 'You stare at it for a moment and think about touching it, but that feels foolhardy.\nYet, you\'re drawn to do so.\nThe light seems to pulse within you the longer you stand there.' },
      { type: 'break' },
      { type: 'text', content: 'After a moment you shake your head and snap out of it.\nNo need to risk making things worse.' },
      { type: 'break' },
      { type: 'text', content: 'So you turn to start the climb that will hopefully be over soon.\nAnd kick something.\nIt crunches against the concrete steps below as it slides away from you.' },
      { type: 'break' },
      { type: 'text', content: 'You turn your flashlight towards the sound and find it.\nA comm.\nOdd place for a comm…' },
      { type: 'break' },
      { type: 'text', content: 'You pick it up and inspect it.\nThe screen is shattered and black.\nFractured. All will be fractured.' },
      { type: 'break' },
      { type: 'text', content: 'You turn it over in your hands and read the name tag.\nNo, that can\'t be right.\nThat\'s not possible.' },
      { type: 'break' },
      { type: 'text', content: 'This comm is stamped with your name.\nYou glance at the one on your wrist, still intact.\nThe one you\'ve had since…\nWell, forever.' },
      { type: 'break' },
      { type: 'text', content: 'Your heart races as you turn the broken comm over in your hands a few more times. The titanium band is broken and jagged, like it was torn apart.' },
      { type: 'break' },
      { type: 'text', content: 'What could do that?' },
      { type: 'break' },
      { type: 'text', content: 'Suddenly the three-toned hum swarms in volume.\nIt\'s so loud you drop the second comm and cover your ears.\nIt reverberates in your chest, nearly knocking the breath out of you.' },
      { type: 'break' },
      { type: 'text', content: 'Then it stops.' },
      { type: 'break' },
      { type: 'text', content: 'Not gets quiet.\nNo.\nStops.\nFor the first time since this all began.' },
      { type: 'break' },
      { type: 'text', content: 'You uncover your ears slowly and take in a deep breath.\nCold sweat runs down your forehead and into your eyes.\nIt stings, but you don\'t care.' },
      { type: 'break' },
      { type: 'text', content: 'Something very wrong just happened.' },
      { type: 'break' },
      { type: 'text', content: 'Your comm buzzes.\nA new message.' },
      { type: 'comm', content: '"The only way out is through…"' },
      { type: 'break' },
      { type: 'text', content: 'Through WHAT?' },
      { type: 'break' },
      { type: 'text', content: 'A new message comes in, as if the sender heard you.' },
      { type: 'comm', content: '"Through the fracture."' },
      { type: 'break' },
      { type: 'text', content: 'The message wipes itself before your eyes and your comm goes dormant.\nYou stare at the black screen and don\'t know what to do.' },
      { type: 'break' },
      { type: 'text', content: 'What do they mean?\nThrough the fracture?\nThere\'s no way that you\'ll fit through that tiny crack.\nNo.\nWay.' },
      { type: 'break' },
      { type: 'text', content: 'So you stand there.\nAngry.\nCold from the air against your sweat soaked clothes.\nConfused.' },
      { type: 'break' },
      { type: 'text', content: 'One way or another, you\'ve got to make a choice.\nUp?\nOr through the crack?' },
    ],
    prompts: [
      {
        id: 'day5b_q1',
        number: 'I',
        text: 'As your character began the climb and found themselves deep in the darkness of the experience, what thoughts were on their mind?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5b_q2',
        number: 'II',
        text: 'How does the second comm with their name on it affect them? What fears or memories does it evoke?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5b_q3',
        number: 'III',
        text: 'What do you think the crack in the wall is? Explain your theory as if you\'re trying to convince a child.',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5b_q4',
        number: 'IV',
        text: 'Through the crack or up the stairs — which decision does your character make and why?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day5b_q5',
        number: 'V',
        text: 'End your entry with this line:',
        endingPrefix: '"Perhaps this is the biggest decision of my life… I hope it leads to freedom."',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day6b',
  },

  {
    id: 'day6b',
    title: 'Day Six: The Choice',
    path: 'B',
    dayNumber: 6,
    location: {
      place: 'Virescent City',
      level: 'Level 10 — Residential District',
      time: 'Day Six: Week 49: 3105  19:37',
    },
    narrative: [
      { type: 'text', content: 'You wake to a massive headache pounding like a bass drum against the front of your skull.\nYou draw in a sharp breath and rub your forehead in response.\nYou open your eyes and the light is nearly unbearable.' },
      { type: 'break' },
      { type: 'text', content: 'All the normal questions run through your mind. Where am I? How did I get here? Why does my head hurt so bad? What\'s the last thing I remember?' },
      { type: 'break' },
      { type: 'text', content: 'What\'s the last thing I remember?' },
      { type: 'break' },
      { type: 'text', content: 'You sit up and go momentarily deaf as the blood rushes to your head. Your whole body hurts like you went on a week long bender and finally fell asleep.' },
      { type: 'break' },
      { type: 'text', content: 'You didn\'t though…\nRight?' },
      { type: 'break' },
      { type: 'text', content: 'No, it\'s not that. This is different. Something fuzzy starts flirting with your memory, but it\'s just out of reach. You can\'t quite grasp it.' },
      { type: 'break' },
      { type: 'text', content: 'You definitely remember waking up in that strange lab. The notes in your handwriting. The fact that you were wearing a lab coat, like you had been the one doing the experiments.' },
      { type: 'break' },
      { type: 'text', content: 'The blank hallway.\nThe disappearing door.\nThe fake copy of yourself.' },
      { type: 'break' },
      { type: 'text', content: 'Wasn\'t there a stairway?\nThere was… wasn\'t there?' },
      { type: 'break' },
      { type: 'text', content: 'Yes, you\'re sure of it now. There was an endless stairway of darkness. You rub your quads and they scream in soreness. Evidence of the climb you made.' },
      { type: 'break' },
      { type: 'text', content: 'Then it all floods back. The stairs, the crack in the wall, the eerie light, the silence, the broken comm.\nYour choice.\nAll of it.' },
      { type: 'break' },
      { type: 'text', content: 'You stand to your feet slowly and allow your head to stop pounding before you move. Looking around you see that you\'re on the street in what looks to be level 10. A quick comm check confirms that.' },
      { type: 'break' },
      { type: 'text', content: 'Shoot.\nIt\'s Day 6?\nHow long were you down there?' },
      { type: 'break' },
      { type: 'text', content: 'No time for worrying about that now. You need to figure out what all this means.' },
      { type: 'break' },
      { type: 'text', content: 'The silence of Virescent City for one. This city is never silent. It hasn\'t been since its inception. You can\'t remember a time where at least the hum of the generators wasn\'t there.\nNo, something is very wrong.\nYou look around and realize the ads are all gone.\nBlank screens.\nNothing more.' },
      { type: 'break' },
      { type: 'text', content: 'The shops and apartment complexes are gone too.\nSealed up, like some overnight magical construction crew came and walled them off with concrete.' },
      { type: 'break' },
      { type: 'text', content: 'You sprint down the street towards your apartment building. What if it\'s gone too? What if it\'s the whole level?\nWhat if it\'s more than one level?\nWhat if it\'s the entire city?' },
      { type: 'break' },
      { type: 'text', content: 'You shove the fear aside that wells up in your chest like lava threatening to erupt from a volcano. As you come close you find yourself muttering a prayer… a plea to anyone who will listen.' },
      { type: 'break' },
      { type: 'text', content: 'Please don\'t let this be real.' },
      { type: 'break' },
      { type: 'text', content: 'You round the corner of the street and see it.\nOh thank the gods.\nOracles be blessed!' },
      { type: 'break' },
      { type: 'text', content: 'The door to your apartment building is still there. You run straight for it and grab the handle before it can disappear like the door did before. The alloy is cold to the touch. A slice of reality held in your hand.' },
      { type: 'break' },
      { type: 'text', content: 'Or so you think… hope.' },
      { type: 'break' },
      { type: 'text', content: 'A moment later you\'re standing in your apartment.\nJust being in the doorway makes you feel less panicked.\nBut, something\'s wrong.' },
      { type: 'break' },
      { type: 'text', content: 'The coffee mug on the counter is what gives it away.\nRed.\nYou don\'t own a red coffee mug.' },
      { type: 'break' },
      { type: 'text', content: 'You run into the living room. The layout is the same, but the furniture is all wrong. It\'s like your eccentric aunt picked out everything in this place. It\'s not your apartment after all.' },
      { type: 'break' },
      { type: 'text', content: 'Well, it is, strictly speaking, but it\'s broken.\nJust like the city.\nJust like the copy.\nJust like…' },
      { type: 'break' },
      { type: 'text', content: 'Your comm buzzes wildly on your arm.\nMultiple notifications at once.' },
      { type: 'break' },
      { type: 'text', content: 'A message from an unknown sender:\n"What\'s the oldest memory you have?"' },
      { type: 'break' },
      { type: 'text', content: 'A health notification stating that your stress levels have been measured to be at dangerously high levels.\n"Meditation guidance?"' },
      { type: 'break' },
      { type: 'text', content: 'Lastly, a notification you\'ve never seen. It looks like… code? You try to decipher it, but it makes no sense. The closest thing you\'ve seen to that was the mainframe to the city. The juxtaposition between Virescent City and The Net.' },
      { type: 'break' },
      { type: 'text', content: 'Yes…\nThis is similar to that, but it\'s like it\'s broken.\nBits of code that should be there are missing.' },
      { type: 'break' },
      { type: 'text', content: 'Another message flashes on the screen:' },
      { type: 'comm', content: '"WHAT IS YOUR OLDEST MEMORY?"\n"THINK!"\n"EVERYTHING DEPENDS ON IT…"' },
      { type: 'break' },
      { type: 'text', content: 'You watch the messages come in one after the other and then fade away. What is your oldest memory?\nYou try to think back.\nYour parents?\nYour siblings?\nChildhood? Your favorite show? Your best friend?' },
      { type: 'break' },
      { type: 'text', content: 'It\'s all a blur.\nLike static or white noise.' },
      { type: 'break' },
      { type: 'text', content: 'The oldest memory you can recall is…\nBut that can\'t be right.' },
      {
        type: 'echo',
        journalKey: 'char.strangeMemory',
        prefix: 'That memory. That one: ',
        suffix: ' — the one that doesn\'t fit your life. The one that has no business being your earliest recollection.',
        fallback: null,
      },
      { type: 'break' },
      { type: 'text', content: 'What\'s that matter anyway?\nHow does your memory have anything to do with the broken code or the silent city or the fake copies of yourself.' },
      { type: 'break' },
      { type: 'text', content: '"How does one know they are the real version of themselves?"' },
      { type: 'break' },
      { type: 'text', content: 'You stare at that message for a long while.\nYou don\'t want to think about that.\nYou can\'t.' },
      { type: 'break' },
      { type: 'text', content: 'But you have to. You know it in your gut. You have to face the music… well, the silence.' },
      { type: 'break' },
      { type: 'text', content: 'A barrage of messages flood in.' },
      { type: 'comm', content: '"Is the city alive or dead?"\n"Was it ever alive at all?"\n"Are you the copy or the original?"\n"Is there any way to know?"' },
      { type: 'break' },
      { type: 'text', content: 'After a moment, one final message appears.' },
      { type: 'comm', content: '"Who are you? The choice is yours. When you know, meet us down below."' },
    ],
    prompts: [
      {
        id: 'day6b_q1',
        number: 'I',
        text: 'Begin by journaling through some of the questions your character has been asking themselves. What emotions and thoughts have risen due to those questions?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6b_q2',
        number: 'II',
        text: 'Write out the thought process that leads up to their decision. What does your character believe about: the city and the glitching? The messages and who\'s sending them? Themselves — are they the original or a copy? Reality itself?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6b_q3',
        number: 'III',
        text: 'Once their decisions are made, one more remains. What are they going to do?\n\n  1. Go below and face whoever is sending the messages.\n  2. Try to communicate with them otherwise.\n  3. Find a way to end the entire experience.\n\nHow does this choice make them feel? What are the first steps?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6b_q4',
        number: 'IV',
        text: 'How does the false memory tie to the incident? Does this help ground your character in their choices, or make them more difficult?',
        placeholder: 'Write in your character\'s voice…',
      },
      {
        id: 'day6b_q5',
        number: 'V',
        text: 'End your entry with this line:',
        endingPrefix: '"The choice wasn\'t easy, but what\'s done is done… Now, it\'s time to face the truth."',
        isFixedEnding: true,
      },
    ],
    nextScene: 'day7',
  },
]
