export const prologueScene = {
  id: 'prologue',
  title: 'Prologue: Below the Noise',
  location: {
    place: 'Virescent City',
    level: 'Level 10 — Residential District',
    time: 'Day One: Week 49: 3105  05:00',
  },
  instruction: 'Read the prologue below, then write a journal entry responding to the prompts at the end.',
  narrative: [
    { type: 'text', content: 'Virescent City never truly sleeps, but tonight it feels muted.' },
    { type: 'text', content: 'The drones glide more quietly than normal.' },
    { type: 'text', content: 'The neon reflection on the perpetually wet pavement seems dimmer somehow.' },
    { type: 'text', content: 'The low electrical hum beneath the sub-levels has shifted by a fraction of a wavelength.' },
    { type: 'break' },
    { type: 'text', content: 'Something is off.' },
    { type: 'break' },
    { type: 'text', content: 'A miniscule change no one else would notice.' },
    { type: 'break' },
    { type: 'text', content: 'But you do.\nYou always have.' },
    { type: 'break' },
    { type: 'text', content: 'Your apartment lights pulse once.\nNot a flicker. Not a power surge. Not even a brown out.\nNo, this is a pulse — synchronized and intentional.\nYou know it in your bones.' },
    { type: 'break' },
    { type: 'text', content: 'And then your comm, dormant on your left wrist, suddenly wakes without your input.\nDidn\'t you change the auto-wake setting to be off?\nYou know you did… weeks ago, right?' },
    { type: 'break' },
    { type: 'text', content: 'A message appears.\nNo sender.\nNo timestamp.' },
    { type: 'break' },
    { type: 'text', content: 'Just four words:' },
    { type: 'comm', content: '"DO YOU HEAR IT?"' },
    { type: 'break' },
    { type: 'text', content: 'Before you can react, the message wipes itself.\nDisappears right before your eyes.\nA soft static hum builds in the walls.\nFor a moment, you swear the entire building is breathing.' },
    { type: 'break' },
    { type: 'text', content: 'Outside your window, one sign across the street goes dark — a green corporate banner you\'ve never noticed before now.' },
    { type: 'break' },
    { type: 'text', content: 'Why that one?\nIs it a part of the message?\nOr is it random chance?' },
    { type: 'break' },
    { type: 'text', content: 'When it lights back up, the slogan has changed.' },
    { type: 'break' },
    { type: 'text', content: 'Now it reads:' },
    { type: 'comm', content: '"WE ARE WAITING BELOW..."' },
  ],
  prompts: [
    {
      id: 'prologue_q1',
      number: 'I',
      text: 'What were you doing just before the lights pulsed?',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'prologue_q2',
      number: 'II',
      text: 'Describe the first physical sensation you felt when you saw the message without a sender.',
      placeholder: 'Write in your character\'s voice…',
    },
    {
      id: 'prologue_q3',
      number: 'III',
      text: 'What does the phrase "WE ARE WAITING BELOW" make you think of?',
      placeholder: 'Write in your character\'s voice…',
    },
    
    {
      id: 'prologue_q4',
      number: 'IV',
      text: 'End your entry with a line that begins with:',
      endingPrefix: '"I think tonight is the first time I\'ve felt…"',
      placeholder: '"I think tonight is the first time I\'ve felt…"',
    },
  ],
  nextScene: 'day1',
}
